In [1]:
import pymongo as mg
import pandas as pd

In [2]:
client = mg.MongoClient(host='mongodb://localhost:27017')
client

MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True)

In [3]:
database = client['db_NHIS']
database

Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'db_NHIS')

In [4]:
collection = database['NSC2_D20']
collection

Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'db_NHIS'), 'NSC2_D20')

In [5]:
cursor = collection.find({})
list_cursor = list(cursor)

In [6]:
df_D20=pd.DataFrame(list_cursor)
df_D20

,_id,RN_INDI,RN_KEY,RN_INST,MDCARE_STRT_DT,FORM_CD,MCARE_SUBJ_CD,SICK_SYM1,OFIJ_TYPE,OPRTN_YN,...,MCARE_RSLT_TYPE,EDC_ADD_RT,ED_RC_TOT_AMT,EDC_SBA,EDC_INSUR_BRDN_AMT,STD_YYYY,SICK_SYM2,HSPTZ_PATH_TYPE,SPCF_SYM_TYPE,FST_HSPTZ_DT
0,64d31117792a7d12dd648ce5,668008,2002030294303,140010,20020325,5,54,K051,0,0,...,5.0,0.15,12480,3500,8980,2002,NaN,NaN,NaN,NaN
1,64d31117792a7d12dd648ce6,440063,2002030797621,139680,20020325,5,53,K006,0,9,...,5.0,0.15,11970,3500,8470,2002,NaN,NaN,NaN,NaN
2,64d31117792a7d12dd648ce7,850654,2002030372244,15041,20020311,5,53,K006,0,9,...,5.0,0.15,11970,3500,8470,2002,NaN,NaN,NaN,NaN
3,64d31117792a7d12dd648ce8,783723,2002010004364,108288,20020121,5,55,K006,NaN,9,...,5.0,0.15,11970,3500,8470,2002,NaN,NaN,NaN,NaN
4,64d31117792a7d12dd648ce9,838106,2002010628708,83960,20020105,5,50,K006,NaN,9,...,5.0,0.15,11970,3500,8470,2002,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12525,64d31118792a7d12dd64bdd2,312513,2015060094233,118846,20150627,5,55,K0300,0,0,...,1.0,0.20,91460,36500,54960,2015,NaN,NaN,NaN,NaN
12526,64d31118792a7d12dd64bdd3,533519,2015042356807,7949,20150407,5,50,K0765,0,0,...,1.0,0.15,86030,25800,60230,2015,NaN,NaN,NaN,NaN
12527,64d31118792a7d12dd64bdd4,423793,2015020324868,47288,20150221,5,55,K0766,0,0,...,1.0,0.15,80490,23600,56890,2015,NaN,NaN,NaN,NaN
12528,64d31118792a7d12dd64bdd5,398604,2015010120760,116017,20150129,5,51,K081,0,9,...,1.0,0.15,488170,244000,244170,2015,NaN,NaN,NaN,NaN
12529,64d31118792a7d12dd64bdd6,398604,2015020991563,116017,20150211,5,51,K081,0,0,...,1.0,0.15,511600,255800,255800,2015,NaN,NaN,NaN,NaN

In [7]:
df_D20.to_csv("./NSC2_D20.csv")