In [1]:
import pymongo as mg
import pandas as pd

In [2]:
client = mg.MongoClient(host='mongodb://localhost:27017')
client

MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True)

In [3]:
database = client['db_NHIS']
database

Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'db_NHIS')

In [4]:
collection = database['NSC2_M20']
collection

Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'db_NHIS'), 'NSC2_M20')

In [5]:
cursor = collection.find({})
list_cursor = list(cursor)

In [6]:
df_M20=pd.DataFrame(list_cursor)
df_M20

,_id,RN_INDI,RN_KEY,RN_INST,MDCARE_STRT_DT,FORM_CD,MCARE_SUBJ_CD,SICK_SYM1,OFIJ_TYPE,OPRTN_YN,...,MCARE_RSLT_TYPE,EDC_ADD_RT,ED_RC_TOT_AMT,EDC_SBA,EDC_INSUR_BRDN_AMT,STD_YYYY,HSPTZ_PATH_TYPE,SICK_SYM2,SPCF_SYM_TYPE,FST_HSPTZ_DT
0,64e6aa403354d2e66dfa2da1,429577,2002070826167,101494,20020729,3,15,B07,0,0,...,5.0,0.15,10590,3000,7590,2002,NaN,NaN,NaN,NaN
1,64e6aa403354d2e66dfa2da2,362517,2002070388352,82780,20020729,3,14,B354,NaN,0,...,5.0,0.15,10590,3000,7590,2002,NaN,NaN,NaN,NaN
2,64e6aa403354d2e66dfa2da3,850526,2002040682051,15540,20020429,3,10,M81,0,0,...,5.0,0.15,10590,3000,7590,2002,NaN,NaN,NaN,NaN
3,64e6aa403354d2e66dfa2da4,334221,2002050374273,47663,20020527,3,14,L739,0,0,...,5.0,0.15,10590,3000,7590,2002,NaN,NaN,NaN,NaN
4,64e6aa403354d2e66dfa2da5,1008348,2002090440633,74788,20020924,3,4,D48,NaN,0,...,5.0,0.15,10590,3000,7590,2002,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137158,64e6aa493354d2e66dfc4567,2078794,2015021769648,39694,20150217,2,11,J_,0,0,...,9.0,0.20,459240,107180,352060,2015,32.0,A099,NaN,NaN
137159,64e6aa493354d2e66dfc4568,179035,2015031741483,85129,20150331,2,10,Z_,0,0,...,1.0,0.20,1296200,307940,988260,2015,32.0,O_,NaN,NaN
137160,64e6aa493354d2e66dfc4569,2088649,2015072309822,128413,20150716,2,11,G039,0,0,...,9.0,0.25,945820,224940,720880,2015,32.0,J303,NaN,NaN
137161,64e6aa493354d2e66dfc456a,857094,2015072016434,119190,20150712,10,0,F_,0,0,...,9.0,0.15,577940,0,577940,2015,32.0,F_,NaN,NaN
137162,64e6aa493354d2e66dfc456b,286070,2015060100839,121839,20150603,2,9,G822,0,0,...,1.0,0.20,2004440,522320,1482120,2015,32.0,F_,NaN,20150603.0

In [8]:
df_M20.to_csv("./NSC2_M20.csv")